remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Better Code Box
description: Find potential issues and code smells in your code
show_downloads: false
